package com.example.alumni.ui.viewmodel

import com.example.alumni.data.Project

data class AppUiState(
    val user: String = "",
    val userEmail : String = "",
    val userPassword: String = "",
    val email: String = "",
    val password: String = "",
    val confirmPassword: String = "",
    val passwordVisible: Boolean = false,
    val confirmPasswordVisible: Boolean = false,
    var fullName: String = "",
    var passingYear: String = "",
    var phoneNo: String = "",
    var linkedIn: String = "",
    var workDetails: String = "",
    var workExperience: String = "",
    var location: String = "",
    val amount: String = "",
    val isEmailWrong: Boolean = false,
    val isPasswordWrong: Boolean = false,
    var isProjectAdded: Boolean = false,
    var isOpeningAdded: Boolean = false,
    var isStoryAdded: Boolean = false,
    var isEventAdded: Boolean = false,
    var isProfileCreated: Boolean = false,
    var successStory: String = "",
    var eventDescription: String = "",
    var eventDate: String = "",
    var eventTime: String = "",
    var eventVenue: String = "",
    var nameStory: String = "",
    var openingName: String = "",
    var companyName: String = "",
    var roleName: String = "",
    var requiredExperience: String = "",
    var openingDescription: String = "",
    var projectName: String = "",
    var projectDescription: String = "",
    var contactEmail: String = "",
    var projectCost: String = "",
    val projectList: List<Project> = emptyList()
)